// The hub landing — the portfolio as a map. Built POCs link to live demos;
// planned ones link to their placeholder card. Grouped by wave.
import { POCS, WAVES, type Poc } from "../portfolio";
import { Commentary, DesignNotes } from "../commentary";

function PocCard({ p }: { p: Poc }) {
  const built = p.status === "built";
  return (
    <a href={`#${p.route}`}
      className={`block rounded-xl ring-1 p-4 shadow-sm transition-colors ${
        built ? "bg-white ring-slate-200 hover:ring-blue-300" : "bg-slate-50 ring-slate-200 hover:ring-slate-300"
      }`}>
      <div className="flex items-center justify-between gap-2">
        <span className="text-sm font-semibold text-slate-800">{p.id} · {p.short}</span>
        {built ? (
          <span className="text-[10px] font-semibold px-2 py-0.5 rounded-full bg-emerald-100 text-emerald-800 ring-1 ring-emerald-200">{p.labPoc} · live</span>
        ) : (
          <span className="text-[10px] font-medium px-2 py-0.5 rounded-full bg-slate-100 text-slate-500 ring-1 ring-slate-200">{p.cost}</span>
        )}
      </div>
      <p className="mt-1.5 text-[12px] leading-snug text-slate-500">{p.question}</p>
    </a>
  );
}

export default function Home() {
  return (
    <div className="max-w-4xl">
      <header className="mb-4">
        <div className="flex items-center gap-2">
          <h1 className="text-xl font-bold tracking-tight">CIE Lab — Prototype Portfolio</h1>
          <span className="text-[11px] font-semibold px-2 py-0.5 rounded bg-slate-800 text-white">reserved · local-first</span>
        </div>
        <p className="text-sm text-slate-500 mt-1 max-w-2xl">
          A deliberately-chosen set of ~10 prototypes exploring the Civic Intelligence Engine design space.
          Each is a point through the morphological field, sequenced by information-per-build and irreversibility.
          We iterate here and <span className="font-medium text-slate-600">converge late</span> — only survivors graduate to the team repo.
          Free LLM/embeddings via TELUS ($0); synthetic + public data only.
        </p>
      </header>

      <div className="mb-5 rounded-lg bg-blue-50 ring-1 ring-blue-200 px-4 py-2.5 text-[13px] text-blue-900">
        <span className="font-semibold">P0 is the trunk.</span> Wave 1 sprays cheap two-way-door probes behind its stable
        record-contract; Wave 3 opens the productization one-way doors. Expect to kill several — that's the cheap learning, not failure.
      </div>

      {WAVES.map((wave) => {
        const items = POCS.filter((p) => p.wave === wave);
        if (!items.length) return null;
        return (
          <section key={wave} className="mb-5">
            <h2 className="text-xs font-semibold uppercase tracking-wide text-slate-400 mb-2">{wave}</h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              {items.map((p) => <PocCard key={p.id} p={p} />)}
            </div>
          </section>
        );
      })}

      <DesignNotes
        title="The design space, in the open"
        subtitle="How CIE decides what to build — the principles, methods, architecture, and choices every prototype is exploring.">
        <Commentary kind="principle" title="AI is a listening aid, never the measurement">
          <p>The north star for the whole venture. Every headline number a candidate sees is derived from <strong>human votes</strong>, never generated by a model. AI earns its place only where it's genuinely good and can't distort the count: <strong>labeling</strong> groups, <strong>paraphrasing</strong> comments, <strong>routing</strong> a question to the right evidence. When the AI is removed, the measurement still stands. This isn't a slogan bolted on afterward — it's an architectural constraint you can see enforced in every prototype.</p>
        </Commentary>
        <Commentary kind="perspective" title="A co-venture with a civic mission">
          <p>CIE is built by <strong>OpenCivics Labs</strong> with <strong>Berggruen (BGI)</strong>, aimed at <strong>campaign constituent-listening</strong>: helping a candidate genuinely hear what a community shares, across its divisions. Pilot 1 is a real campaign. That mission sets the bar — a civic instrument has to be <em>trustworthy under scrutiny</em>, not just clever, which is why the trust layer (validity, scope, provenance) is treated as first-class, not polish.</p>
        </Commentary>
        <Commentary kind="methodology" title="A morphological design space, explored set-based">
          <p>Rather than guess one architecture, we map the <strong>morphological field</strong> — the independent axes of the problem (how you elicit, how you make sense, what surface you show, how deep the methodology goes) and their possible values. Prototypes are <strong>points</strong> chosen through that field. We keep several alive at once and <strong>converge late</strong> (Toyota-style set-based design), letting evidence retire options. Killing a prototype is <em>cheap learning</em>, not failure.</p>
        </Commentary>
        <Commentary kind="choice" title="One-way doors first, two-way doors sprayed">
          <p>Borrowing Bezos's frame: <strong>irreversible</strong> decisions (the record contract, tenancy assumptions) are front-loaded and made deliberately; <strong>reversible</strong> ones (which elicitation, which sensemaking view) are sprayed cheaply as parallel probes. Sequencing by <em>irreversibility × information-per-build</em> is why the trunk (P0) is hardened first and the surface experiments come after — the expensive door is the one you can't walk back through.</p>
        </Commentary>
        <Commentary kind="architecture" title="Ports & adapters around a results contract">
          <p>The engine is <strong>hexagonal</strong>: the core deliberation logic talks to the world only through <strong>ports</strong>, and concrete <strong>adapters</strong> plug in behind them. That's the optionality primitive — a real Pol.is backend, a mock, or a future Comhairle bridge are all just adapters. The prototypes prove this by consuming the same contract from totally different angles without touching the engine.</p>
        </Commentary>
        <Commentary kind="design" title="The record contract is the seam">
          <p>Everything downstream reads one <strong>elicitation-agnostic</strong> artifact — <code>cie.results.v0</code>. Because the contract, not the implementation, is what the UI depends on, <strong>any backend that emits the same shape is swappable</strong>. You can watch this pay off across the portfolio: the dashboard, the graph, and the chat surface are all pure consumers of that JSON. Change the engine underneath and every demo inherits it.</p>
        </Commentary>
        <Commentary kind="choice" title="Build our own core; interoperate, never fork">
          <p>Comhairle (the Scottish-Gov participatory-democracy platform) is <strong>AGPL-3.0</strong>, whose §13 network-copyleft makes a proprietary hosted fork untenable. So the decision is set: <strong>build CIE's own stack</strong> for the pilot, and meet Comhairle at the <em>protocol layer</em> afterward — the Metagov flat-file interoperability standard and Comhairle's own interchange grammar. Interop keeps the door to collaboration open without taking on a license we can't productize under.</p>
        </Commentary>
        <Commentary kind="architecture" title="A free, sovereign stack">
          <p>Every prototype here runs on <strong>free, local TELUS</strong> LLMs and embeddings ($0), so experimentation is unconstrained. That's why the lab can spray probes without a per-call meter. The discipline: POCs use <strong>synthetic + public data only</strong>, so nothing sensitive touches an experiment — real constituent data still routes through a governance gate before any model sees it. Sovereignty (data doesn't leave) is a civic requirement, not a cost optimization.</p>
        </Commentary>
        <Commentary kind="methodology" title="A reproducible trajectory of causality">
          <p>The work leaves a <strong>provenance trail</strong> — borrowing PROV-O's vocabulary (Entity / Activity / Agent) without its RDF weight. The chain <em>transcript → insight → decision → spec → prototype → result</em> falls out as typed, queryable edges, and decisions formalize into <strong>ADRs</strong>. The point: you can always reconstruct <em>why</em> a prototype exists and what evidence retired its alternatives.</p>
        </Commentary>
        <Commentary kind="goal" title="Converge on the surviving intersection">
          <p>The product isn't any single prototype — it's the <strong>intersection of the survivors</strong>. Wave 1 sprays cheap probes behind P0's stable contract; Wave 2 adds surfaces and the heavier methodology bet; Wave 3 opens the productization doors. Whatever holds up across the survivors, ratified by an ADR, <em>becomes the product</em>. This portfolio is the search; convergence is the finding.</p>
        </Commentary>
      </DesignNotes>
    </div>
  );
}
