"""P6 'ask your constituency' — grounded natural-language query over a cie.results.v0 artifact.

The LLM is a *listening aid, never the measurement*. It does two narrow jobs:
  1. routing  — which statements bear on the question (semantic retrieval, free TELUS e5)
  2. phrasing — what the data says, in plain language (free TELUS Gemma)
Every quantity the user sees is rendered from the artifact by the deterministic layer,
never generated by the model. The grounding prompt (GUARDRAIL below) enforces this.

Pipeline:  embed(question,'query')  vs  embed(statements,'passage')  -> cosine top-k
           -> deterministic evidence block (real numbers)  -> Gemma prose + citations
"""
from __future__ import annotations
import numpy as np
import telus


def _cosine(q: np.ndarray, M: np.ndarray) -> np.ndarray:
    q = q / (np.linalg.norm(q) + 1e-9)
    M = M / (np.linalg.norm(M, axis=1, keepdims=True) + 1e-9)
    return M @ q


class Retriever:
    """Embeds the statement set once (free TELUS 'passage'), then answers queries."""

    def __init__(self, artifact: dict):
        self.artifact = artifact
        self.stmts = artifact["statements"]
        texts = [s["text"] for s in self.stmts]
        self.M = np.array(telus.embed(texts, input_type="passage"))

    def top_k(self, question: str, k: int = 4) -> list[tuple[dict, float]]:
        qv = np.array(telus.embed([question], input_type="query")[0])
        sims = _cosine(qv, self.M)
        idx = np.argsort(-sims)[:k]
        return [(self.stmts[i], float(sims[i])) for i in idx]


# ---- the guardrail: the one lever that makes AI a listening aid, not a pollster ----
# These rules are the ethical spine of the product. They are deliberately strict:
# the model may only route + phrase; it may never assert a quantity or upgrade a
# statement's confidence beyond the badge the human votes earned.
GUARDRAIL = (
    "You summarize what a citizen-deliberation dataset shows to a public official. "
    "You are a listening aid, not a pollster. Follow these rules exactly:\n"
    "1. Use ONLY the evidence provided. Never invent statements, numbers, or groups.\n"
    "2. Never state a percentage or count that is not written in the evidence.\n"
    "3. Respect the badge: 'representative-enough' = a genuine shared/bridging view; "
    "'directional' = suggestive but NOT confirmed (say so); 'below-bar' = do NOT claim agreement.\n"
    "4. If the evidence does not answer the question, say so plainly — do not guess.\n"
    "5. Be concise (2-4 sentences). Reference statements by their [ID]. "
    "Describe groups by their label, never as demographics."
)


def _evidence_block(stmt: dict, groups: list[dict]) -> str:
    """Deterministic rendering of one statement's REAL numbers (never via the LLM)."""
    label = {g["group"]: (g.get("ai_label") or f"Group {g['group'] + 1}") for g in groups}
    head = (f'[{stmt["id"]}] "{stmt["text"]}"  '
            f'(badge={stmt["badge"]}, GIC={stmt["gic"]:.2f}, tag={stmt["tag"]})')
    rows = []
    for pg in stmt["per_group"]:
        ar = pg["agree_rate"]
        rows.append(
            f'   - {label[pg["group"]]}: '
            f'{"%.0f%%" % (ar * 100) if ar is not None else "n/a"} agree '
            f'(Wilson floor {pg["wilson_lower"] * 100:.0f}%, n_seen={pg["seen"]})'
        )
    return head + "\n" + "\n".join(rows)


def answer(question: str, artifact: dict, retriever: Retriever, k: int = 4) -> dict:
    hits = retriever.top_k(question, k=k)
    groups = artifact["opinion_groups"]
    evidence = "\n\n".join(_evidence_block(s, groups) for s, _ in hits)
    # Fold the guardrail into a single user turn (Gemma/TELUS role support is unreliable).
    prompt = (
        f"{GUARDRAIL}\n\n"
        f"SCOPE OF THIS DATA: {artifact['scope_banner']}\n\n"
        f"EVIDENCE (the only facts you may use):\n{evidence}\n\n"
        f"QUESTION: {question}\n\n"
        f"Answer using only the evidence above."
    )
    prose = telus.chat(prompt, max_tokens=320, temperature=0.1)
    return {
        "question": question,
        "answer": prose,
        "citations": [s["id"] for s, _ in hits],
        "evidence": [{"id": s["id"], "score": round(sc, 3)} for s, sc in hits],
    }


if __name__ == "__main__":
    import json, sys
    from pathlib import Path
    art = json.load(open(Path(__file__).parent.parent / "web/public/artifact.json"))
    ret = Retriever(art)
    q = " ".join(sys.argv[1:]) or "What do people across all groups actually agree on?"
    out = answer(q, art, ret)
    print("Q:", out["question"])
    print("A:", out["answer"])
    print("cited:", out["citations"])
